apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: follow-semver02
  namespace: argocd
  annotations:
  # prod registry, along with env promotion
    argocd-image-updater.argoproj.io/image-list: ghcr.io/marcpires/gitops-cert-level-2-examples:~1
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default

  source:
    repoURL: https://github.com/marcpires/gitops-cert-level-2-examples.git
    targetRevision: HEAD
    path: ./image-updater/example-app/envs/staging/
   
  destination:
    server: https://kubernetes.default.svc
    namespace: staging

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
